import { PERMISSIONS, type Permission } from "./permissions.js";

export const ORGANIZATION_ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
} as const;

export type OrganizationRole =
  (typeof ORGANIZATION_ROLES)[keyof typeof ORGANIZATION_ROLES];

export const ORGANIZATION_ROLE_PERMISSIONS: Record<
  OrganizationRole,
  readonly Permission[]
> = {
  OWNER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.TOUR_CREATE,
    PERMISSIONS.TOUR_UPDATE,
    PERMISSIONS.TOUR_DELETE,
    PERMISSIONS.DEPARTURE_READ,
    PERMISSIONS.DEPARTURE_CREATE,
    PERMISSIONS.DEPARTURE_UPDATE,
    PERMISSIONS.DEPARTURE_PUBLISH,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_CONFIRM,
    PERMISSIONS.BOOKING_CANCEL,
  ],
  ADMIN: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.TOUR_CREATE,
    PERMISSIONS.TOUR_UPDATE,
    PERMISSIONS.DEPARTURE_READ,
    PERMISSIONS.DEPARTURE_CREATE,
    PERMISSIONS.DEPARTURE_UPDATE,
    PERMISSIONS.DEPARTURE_PUBLISH,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_CONFIRM,
    PERMISSIONS.BOOKING_CANCEL,
  ],
  MEMBER: [
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.DEPARTURE_READ,
    PERMISSIONS.BOOKING_READ,
  ],
};

export function isOrganizationRole(value: string): value is OrganizationRole {
  return Object.values(ORGANIZATION_ROLES).includes(value as OrganizationRole);
}
