import { ALL_PERMISSIONS, PERMISSIONS, type Permission } from "./permissions.js";

export const PLATFORM_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  PLATFORM_SUPPORT: "PLATFORM_SUPPORT",
  PLATFORM_OPERATOR: "PLATFORM_OPERATOR",
} as const;

export type PlatformRole = (typeof PLATFORM_ROLES)[keyof typeof PLATFORM_ROLES];

export const ORGANIZATION_ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE",
  VIEWER: "VIEWER",
} as const;

export type OrganizationRole =
  (typeof ORGANIZATION_ROLES)[keyof typeof ORGANIZATION_ROLES];

export const PLATFORM_ROLE_PERMISSIONS: Record<PlatformRole, Permission[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  PLATFORM_SUPPORT: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.PLATFORM_IDENTITIES_READ,
    PERMISSIONS.PLATFORM_SUPPORT,
  ],
  PLATFORM_OPERATOR: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.PLATFORM_ORGANIZATIONS_MANAGE,
    PERMISSIONS.PLATFORM_IDENTITIES_READ,
  ],
};

export const ORGANIZATION_ROLE_PERMISSIONS: Record<
  OrganizationRole,
  Permission[]
> = {
  OWNER: [
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.BOOKING_MANAGE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.TOUR_MANAGE,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.TOUR_CREATE,
    PERMISSIONS.TOUR_UPDATE,
    PERMISSIONS.TOUR_DELETE,
    PERMISSIONS.CUSTOMER_MANAGE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
  ],
  ADMIN: [
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.BOOKING_MANAGE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.TOUR_MANAGE,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.TOUR_CREATE,
    PERMISSIONS.TOUR_UPDATE,
    PERMISSIONS.TOUR_DELETE,
    PERMISSIONS.CUSTOMER_MANAGE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
  ],
  MANAGER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.TOUR_MANAGE,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.TOUR_CREATE,
    PERMISSIONS.TOUR_UPDATE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
  ],
  EMPLOYEE: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
  ],
  VIEWER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.TOUR_READ,
    PERMISSIONS.CUSTOMER_READ,
  ],
};

export function isPlatformRole(value: string): value is PlatformRole {
  return Object.values(PLATFORM_ROLES).includes(value as PlatformRole);
}

export function isOrganizationRole(value: string): value is OrganizationRole {
  return Object.values(ORGANIZATION_ROLES).includes(value as OrganizationRole);
}
