export const IDENTITY_REPOSITORY = Symbol("IDENTITY_REPOSITORY");
export const SESSION_REPOSITORY = Symbol("SESSION_REPOSITORY");
export const OTP_REPOSITORY = Symbol("OTP_REPOSITORY");
export const MEMBERSHIP_REPOSITORY = Symbol("MEMBERSHIP_REPOSITORY");
export const OTP_DELIVERY = Symbol("OTP_DELIVERY");
export const PROFILE_REPOSITORY = Symbol("PROFILE_REPOSITORY");
